# Generated by Django 4.2.1 on 2023-05-16 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_follower_set_user_following_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following_set',
        ),
        migrations.AlterField(
            model_name='user',
            name='follower_set',
            field=models.ManyToManyField(blank=True, related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
